version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - laundry_network

  customer-service:
    build: ./Customer-service
    container_name: customer_service
    restart: always
    ports:
      - "3003:3002"
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=customer_db
    networks:
      - laundry_network

  laundry-service:
    build: ./Laundry-service
    container_name: laundry_service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=laundry_db
    networks:
      - laundry_network

  order-service:
    build: ./Order-service
    container_name: order_service
    restart: always
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=order_db
    networks:
      - laundry_network

  payment-service:
    build: ./Payment-service
    container_name: payment_service
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=payment_db
    networks:
      - laundry_network

  voucher-service:
    build: ./Voucher-service
    container_name: voucher_service
    restart: always
    ports:
      - "3004:3002"
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=voucher_db
    networks:
      - laundry_network

  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - customer-service
      - laundry-service
      - order-service
      - payment-service
      - voucher-service
    networks:
      - laundry_network

  graphql-gateway:
    build: ./graphql-gateway
    container_name: graphql_gateway
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - customer-service
      - laundry-service
      - order-service
      - payment-service
      - voucher-service
    networks:
      - laundry_network

networks:
  laundry_network:
    driver: bridge

volumes:
  mysql_data:
